### ISSUE TITLE
Maybe version 3 mlf animal 305, m072, m096

### ISSUE THREAD

**Issue by JonasCF** [JonasCF/LSI#6]
In [17]:

x = data_path.replace(' ', '\ ') # This thing you have to do if the data path has whitespaces
name2 = !ls {x + '*.h5'} 
print name2
fs2 = fseq.open_seq(name2[0])
fs2.meta
​
fs2.meta['axes'] = lib.alist_to_scale([(frame_rate, 's'), 
                                       (pixel_size, 'um'),
                                       (pixel_size, 'um')])
​
print fs2.meta
print fs2.shape()
['/Users/cfw958/Desktop/lsi/short_LSI/m096/m096-cropped.h5']
The file /Users/cfw958/Desktop/lsi/short_LSI/m096/m096-cropped.h5 has the following data sets: [u'data']
{'axes': array([(1.0, 's'), (12.758999921780928, 'um'), (12.758999921780928, 'um')], 
      dtype=[('scale', '<f8'), ('units', 'S10')])}
(250, 280)
In [18]:

if len(fslist) > 1:  
    skip = len(fslist) and len(fslist[0]) or 0
    mf2 = fs2.mean_frame((skip, skip + minute2ind(1, dt)))
    p2 = ui.Picker(fs2); p2.start(mean_frame=mf2, cmap='gray',vmin=0, vmax=1000)  
else:
    print "There is nothing to merge"
gcf()
There is nothing to merge
Out[18]:

Overall CBF dynamics
Small problem is, without going through the data, I don't know when MCAO was performed, so what to take as baseline and what time intervals to use for mapping. Let's find out by plotting interquartile range and the median of pixel intensities over time:
In [19]:
# Note I use list comprehesions all the time

fs2.fns = []
## v = np.array([np.percentile(f[f>0], (25,50,75)) for f in fs2.frames()])

IndexError                                Traceback (most recent call last)
<ipython-input-19-7b568ce3ba33> in <module>()
      1 # Note I use list comprehesions all the time
      2 fs2.fns = []
----> 3 v = np.array([np.percentile(f[f>0], (25,50,75)) for f in fs2.frames()])

/Users/cfw958/anaconda/lib/python2.7/site-packages/numpy/lib/function_base.pyc in percentile(a, q, axis, out, overwrite_input, interpolation, keepdims)
   3052     r, k = _ureduce(a, func=_percentile, q=q, axis=axis, out=out,
   3053                     overwrite_input=overwrite_input,
-> 3054                     interpolation=interpolation)
   3055     if keepdims:
   3056         if q.ndim == 0:

/Users/cfw958/anaconda/lib/python2.7/site-packages/numpy/lib/function_base.pyc in _ureduce(a, func, *_kwargs)
   2801         keepdim = [1] \* a.ndim
   2802 
-> 2803     r = func(a, *_kwargs)
   2804     return r, keepdim
   2805 

/Users/cfw958/anaconda/lib/python2.7/site-packages/numpy/lib/function_base.pyc in _percentile(a, q, axis, out, overwrite_input, interpolation, keepdims)
   3141 
   3142         ap.partition(concatenate((indices_below, indices_above)), axis=axis)
-> 3143         x1 = take(ap, indices_below, axis=axis) \* weights_below
   3144         x2 = take(ap, indices_above, axis=axis) \* weights_above
   3145 

/Users/cfw958/anaconda/lib/python2.7/site-packages/numpy/core/fromnumeric.pyc in take(a, indices, axis, out, mode)
    119     except AttributeError:
    120         return _wrapit(a, 'take', indices, axis, out, mode)
--> 121     return take(indices, axis, out, mode)
    122 
    123 

IndexError: cannot do a non-empty take from an empty axes.

**Comment by abrazhe** [comment]
Looks like something wrong with frames read from the file. Do you think it affects only `mlf v3` format?
To check format of the file, you can use the following:

``` python
from imfun import MLFImage

header, table = MLF.read_header('myfile.mlf')
print header
```

what does fs2[0] return? Is it a meaningful frame? 
Alternatively, the source of the problem could be that all values in at least some frames from fs2 are less than zero. How to check:

``` python
np.all([np.any(f>0) for f in fs2])
```

should return `True`

**Comment by JonasCF** [comment]
Exellent idea to test which version, as you saw on github this is what think course the problem. It is only 3 files out of many, which could fit with the ones where I use new moor software, I went back to the old version be course of the errors we had.
but the test does not run:

from imfun import
MLF

#header,table = MLF.read_header(name)

## #print header

ImportError                               Traceback (most
recent call last)

<ipython-input-7-208cd7b3d403> in <module>()

----> 1 from imfun import MLF

```
  2 

  3 #header, table = MLF.read_header(name)

  4 #print header
```

ImportError:
cannot import name MLF

2)fs2[0] return a meaningful frame!
3)I have update the Github issue to hold more info
4)Testing if values in fs2 are below 0 gives error:

np.all([np.any(f>0) for f in
fs2])

---

ValueError                                Traceback (most
recent call last)

<ipython-input-13-bbe91d391341> in <module>()

```
  1 fs2[0]
```

----> 2 np.all([np.any(f>0) for f in fs2])

/Users/cfw958/anaconda/lib/python2.7/site-packages/imfun/fseq.pyc
in **getitem**(self, val)

```
494         return len(self.data)

495     def __getitem__(self, val):
```

--> 496  
x =
self.data[val]

```
497        
```

if len(self.fns) == 0:

```
498             return self.data[val]
```

h5py/_objects.pyx
in h5py._objects.with_phil.wrapper
(-------src-dir--------/h5py/_objects.c:2458)()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper
(-------src-dir--------/h5py/_objects.c:2415)()

/Users/cfw958/anaconda/lib/python2.7/site-packages/h5py/_hl/dataset.pyc in __getitem__(self, args)

```
429 

430         # Perform the dataspace selection.
```

--> 431  
selection = sel.select(self.shape, args, dsid=self.id)

```
432 

433        
```

if selection.nselect == 0:

/Users/cfw958/anaconda/lib/python2.7/site-packages/h5py/_hl/selections.pyc
in select(shape, args, dsid)

```
 97 

 98     sel = SimpleSelection(shape)
```

---> 99  
sel[args]

```
100    
```

return sel

```
101 
```

/Users/cfw958/anaconda/lib/python2.7/site-packages/h5py/_hl/selections.pyc
in __getitem__(self, args)

```
264             return self

265 
```

--> 266  
start, count, step, scalar = _handle_simple(self.shape,args)

```
267 

268        
```

self._id.select_hyperslab(start, count,
step)

/Users/cfw958/anaconda/lib/python2.7/site-packages/h5py/_hl/selections.pyc
in _handle_simple(shape, args)

```
519         else:

520             try:
```

--> 521                 x,y,z =
_translate_int(int(arg), length)

```
522                 s = True

523       
 except TypeError:
```

/Users/cfw958/anaconda/lib/python2.7/site-packages/h5py/_hl/selections.pyc
in _translate_int(exp, length)

```
539 

540     if not 0<=exp<length:
```

--> 541  
raise ValueError("Index (%s) out of range
(0-%s)" % (exp, length-1))

```
542 

543     return exp, 1, 1
```

ValueError:
Index (1293) out of range (0-1292)

Jonas Christoffer Fordsmann
Cand. Med.

Københavns Universitet
Det Sundhedsvidenskabelige Fakultet  
Institut for Neurovidenskab og Farmakologi
TransNeuro Gruppen
Blegdamsvej 3B, 
2200 København N

MOB 27346407
Lokale 24.3.25
Jonas_faxehus@hotmail.com
inf.ku.dk

Date: Sat, 24 Oct 2015 12:40:17 -0700

**Comment by abrazhe** [comment]
I misspelled `MLF` for `MLFImage`, sorry

**Comment by JonasCF** [comment]
It is version 2, so this is not the explanation.using fs2 instead of fs2.frames() gives the same error
I still don't get the >0 test to work:

np.all([np.any(f>0) for f
in fs2])

---

ValueError                                Traceback (most
recent call last)

<ipython-input-16-7c2db679c15b> in <module>()

```
  1 fs2[0]
```

----> 2 np.all([np.any(f>0) for f in fs2])

```
  3 from imfun import MLFImage

  4 

  5 header,
```

table = MLFImage.read_header(name)

/Users/cfw958/anaconda/lib/python2.7/site-packages/imfun/fseq.pyc
in **getitem**(self, val)

```
494         return len(self.data)

495     def __getitem__(self, val):
```

--> 496  
x =
self.data[val]

```
497        
```

if len(self.fns) == 0:

```
498             return self.data[val]
```

h5py/_objects.pyx
in h5py._objects.with_phil.wrapper
(-------src-dir--------/h5py/_objects.c:2458)()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper
(-------src-dir--------/h5py/_objects.c:2415)()

/Users/cfw958/anaconda/lib/python2.7/site-packages/h5py/_hl/dataset.pyc in __getitem__(self, args)

```
429 

430         # Perform the dataspace selection.
```

--> 431  
selection = sel.select(self.shape, args, dsid=self.id)

```
432 

433        
```

if selection.nselect == 0:

/Users/cfw958/anaconda/lib/python2.7/site-packages/h5py/_hl/selections.pyc
in select(shape, args, dsid)

```
 97 

 98     sel = SimpleSelection(shape)
```

---> 99  
sel[args]

```
100    
```

return sel

```
101 
```

/Users/cfw958/anaconda/lib/python2.7/site-packages/h5py/_hl/selections.pyc
in __getitem__(self, args)

```
264             return self

265 
```

--> 266  
start, count, step, scalar = _handle_simple(self.shape,args)

```
267 

268        
```

self._id.select_hyperslab(start, count,
step)

/Users/cfw958/anaconda/lib/python2.7/site-packages/h5py/_hl/selections.pyc
in _handle_simple(shape, args)

```
519         else:

520             try:
```

--> 521                 x,y,z =
_translate_int(int(arg), length)

```
522                 s = True

523             except TypeError:
```

/Users/cfw958/anaconda/lib/python2.7/site-packages/h5py/_hl/selections.pyc
in _translate_int(exp, length)

```
539 

540     if not 0<=exp<length:
```

--> 541  
raise ValueError("Index (%s) out of range
(0-%s)" % (exp, length-1))

```
542 

543     return exp, 1, 1
```

ValueError:
Index (1293) out of range (0-1292)

Jonas Christoffer Fordsmann
Cand. Med.

Københavns Universitet
Det Sundhedsvidenskabelige Fakultet  
Institut for Neurovidenskab og Farmakologi
TransNeuro Gruppen
Blegdamsvej 3B, 
2200 København N

MOB 27346407
Lokale 24.3.25
Jonas_faxehus@hotmail.com
inf.ku.dk

Date: Sat, 24 Oct 2015 13:51:30 -0700

**Comment by abrazhe** [comment]
I see. I'll try to fix

**Comment by JonasCF** [comment]
I think we have the answer, but why would it hold negative values? super strange:In[17]:

fs2[0]

​

from imfun import
MLFImage

​

header, table =
MLFImage.read_header(name)

print header

​

np.all([np.any(f>0) for f in
fs2[:-1]])

Moor FLPI Live Image Data
file V2.0

Out[17]:

False

Jonas Christoffer Fordsmann
Cand. Med.

Københavns Universitet
Det Sundhedsvidenskabelige Fakultet  
Institut for Neurovidenskab og Farmakologi
TransNeuro Gruppen
Blegdamsvej 3B, 
2200 København N

MOB 27346407
Lokale 24.3.25
Jonas_faxehus@hotmail.com
inf.ku.dk

Date: Sat, 24 Oct 2015 15:47:47 -0700

**Comment by JonasCF** [comment]
We now know that, the error arise from having negative values in the movies, do you have an idea of how this could happened and how to fix it in the best way?
I find it very strange since we do no subtraction.

**Comment by JonasCF** [comment]
In [10]:
from imfun import MLFImage

header, table = MLFImage.read_header(name)
print header

np.all([np.any(f>0) for f in fs2[:-1]])

Moor FLPI Live Image Data file V2.0
Out[10]:
False

**Comment by abrazhe** [comment]
Solution variant:

replace the line

``` python
v = np.array([np.percentile(f[f>0], (25,50,75)) for f in fs2.frames()])
```

with the code:

``` python
v = np.zeros((len(fs2),3))
for i,f in enumerate(fs2):
    if np.any(f>0):
        v[i] = np.percentile(f[f>0], (25,50,75))
```
